services:
  app:
    build: .
    container_name: "amur"
    env_file:
      - .env
    ports:
      - 3030:3030
    networks:
      - amur_ntwrk  
    environment:
      - TZ=Asia/Tashkent
   
networks:
  amur_ntwrk: 
    external: true