version: '3.8'

services:
  restaurant-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GIN_MODE=release
      - PORT=8000
    volumes:
      - ./uploads:/root/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - restaurant-network

  # Redis uchun kelajakda
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped
  #   networks:
  #     - restaurant-network

  # PostgreSQL uchun kelajakda
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: restaurant
  #     POSTGRES_USER: restaurant_user
  #     POSTGRES_PASSWORD: restaurant_password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped
  #   networks:
  #     - restaurant-network

volumes:
  # redis_data:
  # postgres_data:
  uploads_data:

networks:
  restaurant-network:
    driver: bridge